CREATE SEQUENCE seq_venta_id
START WITH 120
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP SEQUENCE seq_venta_id;

CREATE SEQUENCE seq_detalle_id
START WITH 20 
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_producto_id
START WITH 51
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_cliente_id
START WITH 20
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO ventas (venta_id, cliente_id, fecha_venta, total_venta)
VALUES (seq_venta_id.NEXTVAL, 5, TO_DATE('08-05-2025', 'DD-MM-YYYY'), 18000);